service: freehold-document-sharing-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: production
    JWT_SECRET: 'freehold-jwt-secret-2024-production-key'
    JWT_REFRESH_SECRET: 'freehold-refresh-secret-2024-production-key'
    AWS_REGION: 'eu-west-2'
    S3_BUCKET_NAME: 'freehold-documents-${self:provider.stage}-${aws:accountId}'
    CORS_ORIGIN: 'https://main.d2n7j8wrtqbawq.amplifyapp.com'
    MAX_FILE_SIZE: '52428800'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 
            - 'arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*:*'
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:PutObjectAcl
          Resource: 
            - 'arn:aws:s3:::freehold-documents-${self:provider.stage}-${aws:accountId}/*'
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: 
            - 'arn:aws:s3:::freehold-documents-${self:provider.stage}-${aws:accountId}'
        - Effect: Allow
          Action:
            - s3:CreateBucket
            - s3:PutBucketPolicy
            - s3:PutBucketCors
          Resource: 
            - 'arn:aws:s3:::freehold-documents-${self:provider.stage}-${aws:accountId}'

functions:
  api:
    handler: src/simple-lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Requested-With
            allowCredentials: true
          integration: lambda-proxy
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Requested-With
            allowCredentials: true
          integration: lambda-proxy

resources:
  Resources:
    DocumentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: freehold-documents-${self:provider.stage}-${aws:accountId}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "https://main.d2n7j8wrtqbawq.amplifyapp.com"
                - "http://localhost:3000"
              MaxAge: 3000
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
  apiGateway:
    restApiId: ${env:API_GATEWAY_REST_API_ID, ''}
    restApiRootResourceId: ${env:API_GATEWAY_ROOT_RESOURCE_ID, ''}
    description: 'Freehold Document Sharing API Gateway'
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/octet-stream'
      - 'image/*'
      - 'application/pdf'